<a href="https://www.kaggle.com/code/pratyushojha12/classification-with-an-academic-83-415-accuracy?scriptVersionId=185210646" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/playground-series-s4e6/sample_submission.csv
/kaggle/input/playground-series-s4e6/train.csv
/kaggle/input/playground-series-s4e6/test.csv

In [2]:
train_df=pd.read_csv("/kaggle/input/playground-series-s4e6/train.csv")
test_df=pd.read_csv("/kaggle/input/playground-series-s4e6/test.csv")
train_df

,id,Marital status,Application mode,Application order,Course,Daytime/evening attendance,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,0,1,1,1,9238,1,1,126.0,1,1,...,0,6,7,6,12.428571,0,11.1,0.6,2.02,Graduate
1,1,1,17,1,9238,1,1,125.0,1,19,...,0,6,9,0,0.000000,0,11.1,0.6,2.02,Dropout
2,2,1,17,2,9254,1,1,137.0,1,3,...,0,6,0,0,0.000000,0,16.2,0.3,-0.92,Dropout
3,3,1,1,3,9500,1,1,131.0,1,19,...,0,8,11,7,12.820000,0,11.1,0.6,2.02,Enrolled
4,4,1,1,2,9500,1,1,132.0,1,19,...,0,7,12,6,12.933333,0,7.6,2.6,0.32,Graduate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76513,76513,1,17,1,9254,1,1,121.0,1,19,...,0,6,8,5,10.600000,0,13.9,-0.3,0.79,Graduate
76514,76514,1,1,6,9254,1,1,125.0,1,1,...,0,6,9,6,13.875000,0,9.4,-0.8,-3.12,Graduate
76515,76515,5,17,1,9085,1,1,138.0,1,37,...,0,5,8,5,11.400000,1,9.4,-0.8,-3.12,Enrolled
76516,76516,1,1,3,9070,1,1,136.0,1,38,...,0,6,0,0,0.000000,0,7.6,2.6,0.32,Dropout
76517,76517,1,1,1,9773,1,1,133.1,1,19,...,0,6,6,6,13.666667,0,15.5,2.8,-4.06,Graduate

In [3]:
test_df

,id,Marital status,Application mode,Application order,Course,Daytime/evening attendance,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,...,Curricular units 1st sem (without evaluations),Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP
0,76518,1,1,1,9500,1,1,141.0,1,3,...,0,0,8,0,0,0.000000,0,13.9,-0.3,0.79
1,76519,1,1,1,9238,1,1,128.0,1,1,...,0,0,6,6,6,13.500000,0,11.1,0.6,2.02
2,76520,1,1,1,9238,1,1,118.0,1,1,...,0,0,6,11,5,11.000000,0,15.5,2.8,-4.06
3,76521,1,44,1,9147,1,39,130.0,1,1,...,0,3,8,14,5,11.000000,0,8.9,1.4,3.51
4,76522,1,39,1,9670,1,1,110.0,1,1,...,0,0,6,9,4,10.666667,2,7.6,2.6,0.32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51007,127525,1,1,2,171,1,1,128.0,1,38,...,0,0,0,0,0,0.000000,0,15.5,2.8,-4.06
51008,127526,2,39,1,9119,1,19,133.1,1,19,...,0,0,5,5,0,0.000000,0,9.4,-0.8,-3.12
51009,127527,1,1,1,171,1,1,127.0,1,1,...,0,0,0,0,0,0.000000,0,15.5,2.8,-4.06
51010,127528,1,1,3,9773,1,1,132.0,1,19,...,0,0,6,9,3,13.000000,0,7.6,2.6,0.32
51011,127529,1,1,1,171,1,1,129.0,1,37,...,0,0,0,0,0,0.000000,0,7.6,2.6,0.32

In [4]:
train_df["Target"] = train_df["Target"].replace({"Graduate":0 ,"Dropout":1,"Enrolled":2})

/tmp/ipykernel_17/793050405.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train_df["Target"] = train_df["Target"].replace({"Graduate":0 ,"Dropout":1,"Enrolled":2})

In [5]:
X = train_df.drop(['Target'], axis=1)
y = train_df[['Target']]
X

,id,Marital status,Application mode,Application order,Course,Daytime/evening attendance,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,...,Curricular units 1st sem (without evaluations),Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP
0,0,1,1,1,9238,1,1,126.0,1,1,...,0,0,6,7,6,12.428571,0,11.1,0.6,2.02
1,1,1,17,1,9238,1,1,125.0,1,19,...,0,0,6,9,0,0.000000,0,11.1,0.6,2.02
2,2,1,17,2,9254,1,1,137.0,1,3,...,0,0,6,0,0,0.000000,0,16.2,0.3,-0.92
3,3,1,1,3,9500,1,1,131.0,1,19,...,0,0,8,11,7,12.820000,0,11.1,0.6,2.02
4,4,1,1,2,9500,1,1,132.0,1,19,...,0,0,7,12,6,12.933333,0,7.6,2.6,0.32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76513,76513,1,17,1,9254,1,1,121.0,1,19,...,0,0,6,8,5,10.600000,0,13.9,-0.3,0.79
76514,76514,1,1,6,9254,1,1,125.0,1,1,...,0,0,6,9,6,13.875000,0,9.4,-0.8,-3.12
76515,76515,5,17,1,9085,1,1,138.0,1,37,...,2,0,5,8,5,11.400000,1,9.4,-0.8,-3.12
76516,76516,1,1,3,9070,1,1,136.0,1,38,...,0,0,6,0,0,0.000000,0,7.6,2.6,0.32
76517,76517,1,1,1,9773,1,1,133.1,1,19,...,0,0,6,6,6,13.666667,0,15.5,2.8,-4.06

In [6]:
from sklearn.preprocessing import RobustScaler

# Assuming X and test_df are your input DataFrames
# Fit the RobustScaler on the training data
scaler = RobustScaler()
scaler.fit(X)

# Transform the training data
X_scaled = scaler.transform(X)

# Transform the test data
test_df_scaled = scaler.transform(test_df)

# Convert the scaled arrays back to DataFrames for better readability
X = pd.DataFrame(X_scaled, columns=X.columns)
test_df = pd.DataFrame(test_df_scaled, columns=test_df.columns)

print("Scaled Training Data:")
print(X.head())

print("Scaled Test Data:")
print(test_df.head())

Scaled Training Data:
         id  Marital status  Application mode  Application order    Course  \
0 -1.000000             0.0         -0.421053                0.0 -0.029038
1 -0.999974             0.0          0.000000                0.0 -0.029038
2 -0.999948             0.0          0.000000                1.0  0.000000
3 -0.999922             0.0         -0.421053                2.0  0.446461
4 -0.999895             0.0         -0.421053                1.0  0.446461

   Daytime/evening attendance  Previous qualification  \
0                         0.0                     0.0
1                         0.0                     0.0
2                         0.0                     0.0
3                         0.0                     0.0
4                         0.0                     0.0

   Previous qualification (grade)  Nacionality  Mother's qualification  ...  \
0                       -0.473333          0.0               -0.500000  ...
1                       -0.540000          0.0                0.000000  ...
2                        0.260000          0.0               -0.444444  ...
3                       -0.140000          0.0                0.000000  ...
4                       -0.073333          0.0                0.000000  ...

   Curricular units 1st sem (without evaluations)  \
0                                             0.0
1                                             0.0
2                                             0.0
3                                             0.0
4                                             0.0

   Curricular units 2nd sem (credited)  Curricular units 2nd sem (enrolled)  \
0                                  0.0                                  0.0
1                                  0.0                                  0.0
2                                  0.0                                  0.0
3                                  0.0                                  2.0
4                                  0.0                                  1.0

   Curricular units 2nd sem (evaluations)  \
0                                0.000000
1                                0.666667
2                               -2.333333
3                                1.333333
4                                1.666667

   Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  \
0                                  0.2                          0.088073
1                                 -1.0                         -3.743119
2                                 -1.0                         -3.743119
3                                  0.4                          0.208734
4                                  0.2                          0.243670

   Curricular units 2nd sem (without evaluations)  Unemployment rate  \
0                                             0.0           0.000000
1                                             0.0           0.000000
2                                             0.0           1.545455
3                                             0.0           0.000000
4                                             0.0          -1.060606

   Inflation rate       GDP
0       -0.347826  0.487106
1       -0.347826  0.487106
2       -0.478261 -0.355301
3       -0.347826  0.487106
4        0.521739  0.000000

[5 rows x 37 columns]
Scaled Test Data:
         id  Marital status  Application mode  Application order    Course  \
0  1.000026             0.0         -0.421053                0.0  0.446461
1  1.000052             0.0         -0.421053                0.0 -0.029038
2  1.000078             0.0         -0.421053                0.0 -0.029038
3  1.000105             0.0          0.710526                0.0 -0.194192
4  1.000131             0.0          0.578947                0.0  0.754991

   Daytime/evening attendance  Previous qualification  \
0                         0.0                     0.0
1                         0.0                     0.0
2                         0.0                     0.0
3                         0.0                    38.0
4                         0.0                     0.0

   Previous qualification (grade)  Nacionality  Mother's qualification  ...  \
0                        0.526667          0.0               -0.444444  ...
1                       -0.340000          0.0               -0.500000  ...
2                       -1.006667          0.0               -0.500000  ...
3                       -0.206667          0.0               -0.500000  ...
4                       -1.540000          0.0               -0.500000  ...

   Curricular units 1st sem (without evaluations)  \
0                                             0.0
1                                             0.0
2                                             0.0
3                                             0.0
4                                             0.0

   Curricular units 2nd sem (credited)  Curricular units 2nd sem (enrolled)  \
0                                  0.0                                  2.0
1                                  0.0                                  0.0
2                                  0.0                                  0.0
3                                  3.0                                  2.0
4                                  0.0                                  0.0

   Curricular units 2nd sem (evaluations)  \
0                               -2.333333
1                               -0.333333
2                                1.333333
3                                2.333333
4                                0.666667

   Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  \
0                                 -1.0                         -3.743119
1                                  0.2                          0.418349
2                                  0.0                         -0.352294
3                                  0.0                         -0.352294
4                                 -0.2                         -0.455046

   Curricular units 2nd sem (without evaluations)  Unemployment rate  \
0                                             0.0           0.848485
1                                             0.0           0.000000
2                                             0.0           1.333333
3                                             0.0          -0.666667
4                                             2.0          -1.060606

   Inflation rate       GDP
0       -0.739130  0.134670
1       -0.347826  0.487106
2        0.608696 -1.255014
3        0.000000  0.914040
4        0.521739  0.000000

[5 rows x 37 columns]

In [7]:
test_df.shape

(51012, 37)

In [8]:
print("\nScaled Test Data:")
print(test_df)

Scaled Test Data:
             id  Marital status  Application mode  Application order  \
0      1.000026             0.0         -0.421053                0.0
1      1.000052             0.0         -0.421053                0.0
2      1.000078             0.0         -0.421053                0.0
3      1.000105             0.0          0.710526                0.0
4      1.000131             0.0          0.578947                0.0
...         ...             ...               ...                ...
51007  2.333246             0.0         -0.421053                1.0
51008  2.333272             1.0          0.578947                0.0
51009  2.333298             0.0         -0.421053                0.0
51010  2.333325             0.0         -0.421053                2.0
51011  2.333351             0.0         -0.421053                0.0

          Course  Daytime/evening attendance  Previous qualification  \
0       0.446461                         0.0                     0.0
1      -0.029038                         0.0                     0.0
2      -0.029038                         0.0                     0.0
3      -0.194192                         0.0                    38.0
4       0.754991                         0.0                     0.0
...          ...                         ...                     ...
51007 -16.484574                         0.0                     0.0
51008  -0.245009                         0.0                    18.0
51009 -16.484574                         0.0                     0.0
51010   0.941924                         0.0                     0.0
51011 -16.484574                         0.0                     0.0

       Previous qualification (grade)  Nacionality  Mother's qualification  \
0                            0.526667          0.0               -0.444444
1                           -0.340000          0.0               -0.500000
2                           -1.006667          0.0               -0.500000
3                           -0.206667          0.0               -0.500000
4                           -1.540000          0.0               -0.500000
...                               ...          ...                     ...
51007                       -0.340000          0.0                0.527778
51008                        0.000000          0.0                0.000000
51009                       -0.406667          0.0               -0.500000
51010                       -0.073333          0.0                0.000000
51011                       -0.273333          0.0                0.500000

       ...  Curricular units 1st sem (without evaluations)  \
0      ...                                             0.0
1      ...                                             0.0
2      ...                                             0.0
3      ...                                             0.0
4      ...                                             0.0
...    ...                                             ...
51007  ...                                             0.0
51008  ...                                             0.0
51009  ...                                             0.0
51010  ...                                             0.0
51011  ...                                             0.0

       Curricular units 2nd sem (credited)  \
0                                      0.0
1                                      0.0
2                                      0.0
3                                      3.0
4                                      0.0
...                                    ...
51007                                  0.0
51008                                  0.0
51009                                  0.0
51010                                  0.0
51011                                  0.0

       Curricular units 2nd sem (enrolled)  \
0                                      2.0
1                                      0.0
2                                      0.0
3                                      2.0
4                                      0.0
...                                    ...
51007                                 -6.0
51008                                 -1.0
51009                                 -6.0
51010                                  0.0
51011                                 -6.0

       Curricular units 2nd sem (evaluations)  \
0                                   -2.333333
1                                   -0.333333
2                                    1.333333
3                                    2.333333
4                                    0.666667
...                                       ...
51007                               -2.333333
51008                               -0.666667
51009                               -2.333333
51010                                0.666667
51011                               -2.333333

       Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  \
0                                     -1.0                         -3.743119
1                                      0.2                          0.418349
2                                      0.0                         -0.352294
3                                      0.0                         -0.352294
4                                     -0.2                         -0.455046
...                                    ...                               ...
51007                                 -1.0                         -3.743119
51008                                 -1.0                         -3.743119
51009                                 -1.0                         -3.743119
51010                                 -0.4                          0.264220
51011                                 -1.0                         -3.743119

       Curricular units 2nd sem (without evaluations)  Unemployment rate  \
0                                                 0.0           0.848485
1                                                 0.0           0.000000
2                                                 0.0           1.333333
3                                                 0.0          -0.666667
4                                                 2.0          -1.060606
...                                               ...                ...
51007                                             0.0           1.333333
51008                                             0.0          -0.515152
51009                                             0.0           1.333333
51010                                             0.0          -1.060606
51011                                             0.0          -1.060606

       Inflation rate       GDP
0           -0.739130  0.134670
1           -0.347826  0.487106
2            0.608696 -1.255014
3            0.000000  0.914040
4            0.521739  0.000000
...               ...       ...
51007        0.608696 -1.255014
51008       -0.956522 -0.985673
51009        0.608696 -1.255014
51010        0.521739  0.000000
51011        0.521739  0.000000

[51012 rows x 37 columns]

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [10]:
!pip install catboost optuna

Requirement already satisfied: catboost in /opt/conda/lib/python3.10/site-packages (1.2.5)
Requirement already satisfied: optuna in /opt/conda/lib/python3.10/site-packages (3.6.1)
Requirement already satisfied: graphviz in /opt/conda/lib/python3.10/site-packages (from catboost) (0.20.3)
Requirement already satisfied: matplotlib in /opt/conda/lib/python3.10/site-packages (from catboost) (3.7.5)
Requirement already satisfied: numpy>=1.16.0 in /opt/conda/lib/python3.10/site-packages (from catboost) (1.26.4)
Requirement already satisfied: pandas>=0.24 in /opt/conda/lib/python3.10/site-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /opt/conda/lib/python3.10/site-packages (from catboost) (1.11.4)
Requirement already satisfied: plotly in /opt/conda/lib/python3.10/site-packages (from catboost) (5.18.0)
Requirement already satisfied: six in /opt/conda/lib/python3.10/site-packages (from catboost) (1.16.0)
Requirement already satisfied: alembic>=1.5.0 in /opt/conda/lib/python3.10/site-packages (from optuna) (1.13.1)
Requirement already satisfied: colorlog in /opt/conda/lib/python3.10/site-packages (from optuna) (6.8.2)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.10/site-packages (from optuna) (21.3)
Requirement already satisfied: sqlalchemy>=1.3.0 in /opt/conda/lib/python3.10/site-packages (from optuna) (2.0.25)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.10/site-packages (from optuna) (4.66.4)
Requirement already satisfied: PyYAML in /opt/conda/lib/python3.10/site-packages (from optuna) (6.0.1)
Requirement already satisfied: Mako in /opt/conda/lib/python3.10/site-packages (from alembic>=1.5.0->optuna) (1.3.5)
Requirement already satisfied: typing-extensions>=4 in /opt/conda/lib/python3.10/site-packages (from alembic>=1.5.0->optuna) (4.9.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/conda/lib/python3.10/site-packages (from packaging>=20.0->optuna) (3.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.10/site-packages (from pandas>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas>=0.24->catboost) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.10/site-packages (from pandas>=0.24->catboost) (2023.4)
Requirement already satisfied: greenlet!=0.4.17 in /opt/conda/lib/python3.10/site-packages (from sqlalchemy>=1.3.0->optuna) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib->catboost) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.10/site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.10/site-packages (from matplotlib->catboost) (4.47.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib->catboost) (1.4.5)
Requirement already satisfied: pillow>=6.2.0 in /opt/conda/lib/python3.10/site-packages (from matplotlib->catboost) (9.5.0)
Requirement already satisfied: tenacity>=6.2.0 in /opt/conda/lib/python3.10/site-packages (from plotly->catboost) (8.2.3)
Requirement already satisfied: MarkupSafe>=0.9.2 in /opt/conda/lib/python3.10/site-packages (from Mako->alembic>=1.5.0->optuna) (2.1.3)

In [11]:
# import pandas as pd
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import accuracy_score
# from catboost import CatBoostClassifier
# import optuna

# # Assuming X and y are your features and target
# # For illustration, let's create some dummy data
# # X, y = some_data_loading_function()

# # Split the data (assuming X and y are already defined)
# # Example: X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# # Define the objective function
# def objective(trial):
#     param = {
#         'iterations': trial.suggest_int('iterations', 100, 1000),
#         'depth': trial.suggest_int('depth', 4, 10),
#         'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 1e-1),
#         'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-2, 10),
#         'border_count': trial.suggest_int('border_count', 32, 255),
#         'random_strength': trial.suggest_loguniform('random_strength', 1e-2, 10),
#         'bagging_temperature': trial.suggest_loguniform('bagging_temperature', 0.01, 100.00),
#         'od_type': 'Iter',
#         'od_wait': trial.suggest_int('od_wait', 10, 50)
#     }

#     model = CatBoostClassifier(**param, verbose=0)
#     model.fit(X_train, y_train, eval_set=(X_test, y_test), early_stopping_rounds=50, verbose=0)

#     preds = model.predict(X_test)
#     accuracy = accuracy_score(y_test, preds)
#     return accuracy

# # Create a study and optimize the objective function
# study = optuna.create_study(direction='maximize')
# study.optimize(objective, n_trials=100)

# # Get the best parameters
# print('Best trial:')
# trial = study.best_trial
# print('  Value: {}'.format(trial.value))
# print('  Params: ')
# for key, value in trial.params.items():
#     print('    {}: {}'.format(key, value))

# # Train the final model using the best parameters
# best_params = trial.params
# best_model = CatBoostClassifier(**best_params)
# best_model.fit(X_train, y_train)

# # Evaluate the model on the test data
# preds = best_model.predict(X_test)
# final_accuracy = accuracy_score(y_test, preds)
# print('Final Accuracy on test data: {}'.format(final_accuracy))

In [12]:
from catboost import CatBoostClassifier, Pool
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


model = CatBoostClassifier(
    iterations=464,
    depth=6,
    learning_rate=0.09895241567562836,
    l2_leaf_reg=9.985962934032957,
    border_count=37,
    random_strength=0.12603980788866026,
    bagging_temperature=0.05779942338447749,
    od_wait=42,
    eval_metric='Accuracy',
    verbose=100
)

# Train the model
model.fit(X_train, y_train, eval_set=(X_test, y_test), early_stopping_rounds=100)

# Predict on the test set
y_pred = model.predict(X_test)

# Calculate and print the accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy: {accuracy}")

0:	learn: 0.8074787	test: 0.8054757	best: 0.8054757 (0)	total: 94.7ms	remaining: 43.9s
100:	learn: 0.8298428	test: 0.8290643	best: 0.8295870 (99)	total: 3.26s	remaining: 11.7s
200:	learn: 0.8353808	test: 0.8318740	best: 0.8318740 (199)	total: 6.19s	remaining: 8.1s
300:	learn: 0.8381253	test: 0.8325274	best: 0.8327235 (267)	total: 9.55s	remaining: 5.17s
400:	learn: 0.8413108	test: 0.8344224	best: 0.8345531 (381)	total: 12.4s	remaining: 1.95s
463:	learn: 0.8428791	test: 0.8348798	best: 0.8348798 (463)	total: 14.2s	remaining: 0us

bestTest = 0.83487977
bestIteration = 463

Test Accuracy: 0.8348797699947726

In [13]:
# import tensorflow as tf
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Dense, Dropout
# from tensorflow.keras.optimizers import Adam
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import accuracy_score


# # Define the ANN architecture
# model = Sequential()
# model.add(Dense(64, input_dim=X_train.shape[1], activation='relu'))
# model.add(Dropout(0.5))
# model.add(Dense(32, activation='relu'))
# model.add(Dropout(0.5))
# model.add(Dense(1, activation='sigmoid'))  # Assuming binary classification

# # Compile the model
# model.compile(optimizer=Adam(learning_rate=0.001), loss='binary_crossentropy', metrics=['accuracy'])

# # Train the model
# history = model.fit(X_train, y_train, epochs=50, batch_size=32, validation_data=(X_test, y_test), verbose=1)

# # Predict on the test set
# pred = (model.predict(X_test) > 0.5).astype("int32")

# # Calculate and print the accuracy
# accuracy = accuracy_score(y_test, pred)
# print(f"Test Accuracy: {accuracy}")

In [14]:
#!pip install lightgbm optuna

In [15]:
# import lightgbm as lgb
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import accuracy_score

# # Sample data preparation (replace with your actual data)
# # X, y should be your features and labels
# # X, y = ...

# # Split the dataset into training and testing sets
# #X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# # Define the hyperparameters for LightGBM
# params = {
#     'objective': 'binary',
#     'metric': 'binary_error',
#     'boosting_type': 'gbdt',
#     'learning_rate': 0.1,
#     'num_leaves': 31,
#     'max_depth': -1,
#     'min_data_in_leaf': 20,
#     'lambda_l1': 0.0,
#     'lambda_l2': 0.0,
#     'feature_fraction': 0.8,
#     'bagging_fraction': 0.8,
#     'bagging_freq': 0,
#     'min_child_samples': 20,
#     'verbosity': -1,
#     'seed': 42
# }

# # Create a LightGBM dataset
# train_data = lgb.Dataset(X_train, label=y_train)
# test_data = lgb.Dataset(X_test, label=y_test, reference=train_data)

# # Train the model
# model = lgb.train(params, train_data, valid_sets=[test_data])

# # Predict on the test set
# y_pred = model.predict(X_test, num_iteration=model.best_iteration)
# y_pred_binary = [1 if x > 0.5 else 0 for x in y_pred]

# # Calculate and print the accuracy
# accuracy = accuracy_score(y_test, y_pred_binary)
# print(f"Test Accuracy: {accuracy}")

##ANN is not working as good as catboost hence use catboost

In [16]:
pred = model.predict(test_df)
np.unique(pred)

array([0, 1, 2])

In [17]:
(pred).shape

(51012, 1)

In [18]:
class_mapping = {0: 'Graduate', 1: 'Dropout', 2: 'Enrolled',}

In [19]:
pred_mapped = np.vectorize(class_mapping.get)(pred)
(pred_mapped)

array([['Dropout'],
       ['Graduate'],
       ['Graduate'],
       ...,
       ['Dropout'],
       ['Dropout'],
       ['Dropout']], dtype='<U8')

In [20]:
test_df1=pd.read_csv('/kaggle/input/playground-series-s4e6/test.csv')
test_df1

,id,Marital status,Application mode,Application order,Course,Daytime/evening attendance,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,...,Curricular units 1st sem (without evaluations),Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP
0,76518,1,1,1,9500,1,1,141.0,1,3,...,0,0,8,0,0,0.000000,0,13.9,-0.3,0.79
1,76519,1,1,1,9238,1,1,128.0,1,1,...,0,0,6,6,6,13.500000,0,11.1,0.6,2.02
2,76520,1,1,1,9238,1,1,118.0,1,1,...,0,0,6,11,5,11.000000,0,15.5,2.8,-4.06
3,76521,1,44,1,9147,1,39,130.0,1,1,...,0,3,8,14,5,11.000000,0,8.9,1.4,3.51
4,76522,1,39,1,9670,1,1,110.0,1,1,...,0,0,6,9,4,10.666667,2,7.6,2.6,0.32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51007,127525,1,1,2,171,1,1,128.0,1,38,...,0,0,0,0,0,0.000000,0,15.5,2.8,-4.06
51008,127526,2,39,1,9119,1,19,133.1,1,19,...,0,0,5,5,0,0.000000,0,9.4,-0.8,-3.12
51009,127527,1,1,1,171,1,1,127.0,1,1,...,0,0,0,0,0,0.000000,0,15.5,2.8,-4.06
51010,127528,1,1,3,9773,1,1,132.0,1,19,...,0,0,6,9,3,13.000000,0,7.6,2.6,0.32
51011,127529,1,1,1,171,1,1,129.0,1,37,...,0,0,0,0,0,0.000000,0,7.6,2.6,0.32

In [21]:
pred_mapped.shape

(51012, 1)

In [22]:
test_df1['id'].shape

(51012,)

In [23]:
# Ensure predictions are a 1-dimensional array
if pred_mapped.ndim > 1:
    pred_mapped = pred_mapped.flatten()

# Ensure 'id' column from test_df1 is preserved
submission = pd.DataFrame({'id': test_df1['id'], 'Target': pred_mapped})

# Check the submission DataFrame
print(submission.head())
print(f"Submission data shape: {submission.shape}")

# Save submission
submission.to_csv('submission.csv', index=False)

      id    Target
0  76518   Dropout
1  76519  Graduate
2  76520  Graduate
3  76521  Graduate
4  76522  Enrolled
Submission data shape: (51012, 2)

In [24]:
submission.to_csv('submission.csv', index=False)